name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main 
       - main.yml

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build # Or your build command

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: mom-s-vyanjan-tiffin # Replace with your Firebase project ID
          # Optional: Specify the target hosting site if you have multiple
          # target: firebase-hosting-target
